# Funding links for VulnLab Scanner
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [FARLEY-PIEDRAHITA-OROZCO]
patreon: # Add if available
open_collective: # Add if available
ko_fi: # Add if available
buy_me_a_coffee: # Add if available
custom: ["https://paypal.me/vulnlab"]  # Add if available
